name: Build and Push orders-service to ECR

on:
  push:
    branches:
      - main
    paths:
      - 'ordersservice/**'
      - '.github/workflows/push-orders-to-ecr.yml'
  workflow_dispatch: # Te añadí esto por si quieres lanzarlo manualmente

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: sa-east-1
  ECR_REPOSITORY: orders-service
  SERVICE_PATH: ordersservice

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials with OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::637423306867:role/github-actions-ecr-push-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag and push Docker image
        id: build-image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          # Definimos el tag corto (7 caracteres)
          SHA_TAG=${GITHUB_SHA::7}
          
          # Construimos la imagen
          docker build \
            -t $REGISTRY/$ECR_REPOSITORY:$SHA_TAG \
            -t $REGISTRY/$ECR_REPOSITORY:latest \
            ./$SERVICE_PATH

          # Subimos ambos tags
          docker push $REGISTRY/$ECR_REPOSITORY:$SHA_TAG
          docker push $REGISTRY/$ECR_REPOSITORY:latest
          
          # Exportamos el tag para el siguiente paso
          echo "image_tag=$SHA_TAG" >> $GITHUB_OUTPUT

      - name: Show pushed image
        run: |
          echo "Pushed to: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ steps.build-image.outputs.image_tag }}"
